config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  root 'pages#home'
  get '/dashboard' => 'users#show', as: :user_root

  resources :groups, only: [:new, :create, :show]
  resources :invitations, only: [:create]
  resources :list_items, only: [:create, :destroy]
  resources :memberships, only: [:new, :create]
  resources :users, only: [:new]
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_secure_token

  belongs_to :admin_user, foreign_key: :user_id, class_name: 'User'

  has_many :invitations, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :lists, dependent: :destroy

  validates :user_id, numericality: true
  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id, message: "already used" }

  after_create :create_admin_membership!

  private

  def create_admin_membership!
    Membership.create!(group: self, user: self.admin_user)
  end

end

app/models/group_form.rb
class GroupForm
  include ActiveModel::Model
  include ActiveModel::Validations

  GROUP_FIELDS = [:name]

  delegate *GROUP_FIELDS, to: :group

  validates :name, presence: true

  def self.model_name
    ActiveModel::Name.new(self, nil, 'Group')
  end

  def initialize(current_user, group = nil)
    @user = current_user
    @group = group
  end

  def group
    @group ||= Group.new(user_id: @user.id)
  end

  def submit(group_params, emails_for_invitations)
    group.name = group_params[:name]
    begin
      if valid?
        group.transaction do
          group.save!
          Invitation.create_invites!(group, emails_for_invitations)
        end
        return true
      else
        return false
      end
    rescue ActiveRecord::RecordInvalid => e
      add_errors(e.record)
      return false
    end
  end

  private

  def add_errors(object)
    object.errors.messages.each { |attr, msg| self.errors.add(attr, msg.uniq.join) }
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group_form = GroupForm.new(current_user)
    authorize(@group_form.group)
  end

  def create
    @group_form = GroupForm.new(current_user)
    authorize(@group_form.group)
    if @group_form.submit(group_params, params[:group][:invitation_emails])
      redirect_to @group_form.group, notice: 'Group successfully created!'
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    authorize(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

end

app/views/groups/_form.html.haml
= form_for group_form do |f|

  - handle_errors(group_form)

  %fieldset.form-group
    = f.label(:name, 'Group name')
    = f.text_field(:name, autofocus: true, class: 'form-control')

  %fieldset.form-group
    = label_tag(:group_invitation_emails, raw('Invite by email <span>(one email per line)</span>'))
    = text_area_tag('group[invitation_emails]', nil, class: 'form-control')

  = f.submit('Create Group', data: {disable_with: 'Saving...'}, class: 'btn btn-primary')
  = link_to('Cancel', user_root_path, class: 'btn btn-danger')

app/views/groups/_group.html.haml
.row.group
  .col-sm-12
    %h2= group.decorate.display_name
    = link_to('Group Details', group, class: 'group-details')
  .col-sm-12.col-md-6
    = render current_user.list_for_group(group)
  .col-sm-12.col-md-6
    = render 'lists/paired_list', list: current_user.paired_list_for_group(group)

app/views/groups/_invitations.html.haml
- group ||= @group

- if group.invitations.open.any?
  %h2 Pending Invitations

  %ul
    - group.invitations.open.each do |invitation|
      %li= invitation.email

app/views/groups/_members.html.haml
- group ||= @group

%h2 Current Members

%ul
  - group.users.each do |user|
    %li
      - if policy(group).update?
        = user.name
      - else
        = user.first_name

app/views/groups/new.html.haml
- title('Create a Group')

%h1 Create a Group

.description
  Ready to create a group? Just pick a name and enter the email addresses of friends you want to send invitations to. Don't worry, you can always add more friends later.

= render 'form', group_form: @group_form

app/views/groups/show.html.haml
- title(@group.name)

%h1= @group.name

= render 'groups/members', group: @group

- if policy(@group).update?
  %h3 Invite New Users

  %div
    Send new invitations
    = render 'invitations/form', invitation: Invitation.new(group: @group)

  %div
    Share the following token to allow other users to join your group:
    .token= @group.token